const { Pool } = require('pg');
const { ensureStore } = require('./fileStore');

const shouldUseSsl = String(process.env.DB_SSL || '').toLowerCase() === 'true';
const sslRejectUnauthorized =
  String(process.env.DB_SSL_REJECT_UNAUTHORIZED || 'false').toLowerCase() !== 'false';

const pool = new Pool({
  host: process.env.DB_HOST,
  port: Number(process.env.DB_PORT || 5432),
  user: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_NAME,
  ssl: shouldUseSsl
    ? {
        rejectUnauthorized: sslRejectUnauthorized
      }
    : undefined,
  max: 10
});

const ensureSchema = async () => {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      email VARCHAR(150) NOT NULL UNIQUE,
      phone VARCHAR(20) NOT NULL,
      password_hash VARCHAR(255) NOT NULL,
      role VARCHAR(20) NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin')),
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS vehicles (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      vehicle_number VARCHAR(30) NOT NULL,
      vehicle_type VARCHAR(30) NOT NULL,
      owner_name VARCHAR(100) NOT NULL,
      contact_phone VARCHAR(20) NOT NULL,
      emergency_contact VARCHAR(20) NOT NULL,
      qr_code_url TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS scans (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      vehicle_id INTEGER NOT NULL REFERENCES vehicles(id) ON DELETE CASCADE,
      scan_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      ip_address VARCHAR(100) NOT NULL,
      device VARCHAR(255) NOT NULL,
      latitude NUMERIC(10, 7),
      longitude NUMERIC(10, 7)
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS password_reset_tokens (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      token_hash VARCHAR(255) NOT NULL,
      expires_at TIMESTAMPTZ NOT NULL,
      used_at TIMESTAMPTZ,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  `);

  await pool.query('CREATE INDEX IF NOT EXISTS idx_vehicles_user_id ON vehicles(user_id)');
  await pool.query('CREATE INDEX IF NOT EXISTS idx_scans_vehicle_id ON scans(vehicle_id)');
  await pool.query('CREATE INDEX IF NOT EXISTS idx_scans_scan_time ON scans(scan_time)');
  await pool.query('CREATE INDEX IF NOT EXISTS idx_reset_user_id ON password_reset_tokens(user_id)');
  await pool.query('CREATE INDEX IF NOT EXISTS idx_reset_token_hash ON password_reset_tokens(token_hash)');
};

let storageMode = 'postgres';
let startupError = null;

const ensureStorageReady = async () => {
  try {
    await pool.query('SELECT 1');
    await ensureSchema();
    storageMode = 'postgres';
    startupError = null;
    return storageMode;
  } catch (error) {
    startupError = error;
    storageMode = 'file';
    await ensureStore();
    return storageMode;
  }
};

const getStorageMode = () => storageMode;

const getStartupError = () => startupError;

const isUsingFileStore = () => storageMode === 'file';

module.exports = {
  pool,
  ensureStorageReady,
  getStorageMode,
  getStartupError,
  isUsingFileStore,
  ensureSchema
};
